Bump version to 1.1.5, use SBDIR

diff --git a/libquicktime.SlackBuild b/libquicktime.SlackBuild
--- a/libquicktime.SlackBuild
+++ b/libquicktime.SlackBuild
@@ -2,18 +2,18 @@
 #
 # SlackBuild for LibQuickTime
 # Written by Georgi D. Sotirov <gdsotirov@dir.bg>
+# Vist SlackPack at http://sotirov-bg.net/slackpack/
 #
 
 . ../slack-package.conf
 
 NAME=libquicktime
-VERSION=1.1.3
+VERSION=1.1.5
 ARCH=${ARCH:-i486}
-BUILD=1
+BUILD=${BUILD:-1}
 
 TMP=${TMP:-/tmp}
 CWD=${CWD:-`pwd`}
-PKG_DIR=${PKG_DIR:-/tmp}
 
 if [ ! -e $TMP ]; then
   mkdir -p $TMP # location to build the source
@@ -34,7 +34,7 @@ mkdir -p $PKG
 
 # Extract and fix source
 cd $TMP
-tar xzvf $CWD/$NAME-$VERSION.tar.gz
+tar -xvf $CWD/$NAME-$VERSION.tar.gz
 cd $SRC
 fix_source
 
@@ -45,17 +45,13 @@ CXXFLAGS=$SLKCFLAGS \
             --host=$ARCH-slackware-linux \
             --prefix=/usr \
             --mandir=/usr/man \
+            --docdir=/usr/doc/$NAME-$VERSION \
             --enable-shared=yes \
             --enable-static=no \
-            --enable-gpl \
-            --without-x264 || exit 1
+            --enable-gpl || exit 1
 
 # Build & install
 make -j4 || exit 1
-
-PKG="$TMP/package-$NAME"
-mkdir -p $PKG
-
 make -e DESTDIR=$PKG install || exit 3
 
 # Prepare
@@ -69,13 +65,14 @@ install -m 644 $CWD/slack-desc     $PKG/install
 install -m 644 $CWD/slack-required $PKG/install
 install -m 644 $CWD/slack-suggests $PKG/install
 
-mkdir -p $PKG/usr/src/slackbuilds/$NAME-$VERSION
-install -m 644 $CWD/slack-desc       $PKG/usr/src/slackbuilds/$NAME-$VERSION
-install -m 644 $CWD/slack-required   $PKG/usr/src/slackbuilds/$NAME-$VERSION
-install -m 644 $CWD/slack-suggests   $PKG/usr/src/slackbuilds/$NAME-$VERSION
-install -m 644 $CWD/$NAME.SlackBuild $PKG/usr/src/slackbuilds/$NAME-$VERSION
+SBDIR=$PKG/usr/src/slackbuilds/$NAME-$VERSION
+mkdir -p $SBDIR
+install -m 644 $CWD/slack-desc       $SBDIR/slack-desc
+install -m 644 $CWD/slack-required   $SBDIR/slack-required
+install -m 644 $CWD/slack-suggests   $SBDIR/slack-suggests
+install -m 644 $CWD/$NAME.SlackBuild $SBDIR/$NAME.SlackBuild
 
-# Pack
+# Assemble
 cd $PKG
 PKGNAME=$NAME-$VERSION-$ARCH-$BUILD$MYIN
 makepkg -l y -c n $PKG_DIR/$PKGNAME.txz
@@ -83,6 +80,7 @@ cd $PKG_DIR
 md5sum $PKGNAME.txz > $PKGNAME.txz.md5
 cat $PKG/install/slack-desc > $PKG_DIR/$PKGNAME.txt
 
+# Cleanup (optionally)
 if [ "$1" == "--cleanup" ]; then
   rm -r $SRC
   rm -r $PKG
